import { vars } from "nativewind";
import { ThemeColorsOptions, ThemeOptions } from "./theme";

export const defaultTheme: ThemeOptions = {
    "mode": "dark",
    "radius": "0.5rem",
    "scrollbarWidth": "0.5rem",
    "scrollbarHeight": "0.5rem",
    "scrollbarBorderRadius": "5px",
    "scrollbarThumbRounded": "9999px"
}

/**
    Material 3
    light
        primary                 -> tone 40
        on-primary              -> tone 100

        primary-container       -> tone 90
        on-primary-container    -> tone 10

        primary-fixed           -> tone 90
        primary-fixed-dim       -> tone 80

        on-primary-fixed         -> tone 10
        on-primary-fixed-variant -> tone 30

        surface                 -> neutral tone 98
        surface-dim             -> neutral tone 87
        surface-bright          -> neutral tone 98

        surface-container-low   -> neutral tone 96
        surface-container       -> neutral tone 94
        surface-container-high  -> neutral tone 92

        outline                 -> neutral-variant tone 50
        primary                 -> tone 80
    
    dark
        primary                 -> tone 80
        on-primary              -> tone 20

        primary-container       -> tone 30
        on-primary-container    -> tone 90

        primary-fixed           -> SAME as light
        primary-fixed-dim       -> SAME as light

        on-primary-fixed         -> SAME as light
        on-primary-fixed-variant -> SAME as light

        surface                 -> neutral tone 6
        surface-dim             -> neutral tone 6
        surface-bright          -> neutral tone 24

        surface-container-low   -> neutral tone 10
        surface-container       -> neutral tone 12
        surface-container-high  -> neutral tone 17

        outline                 -> neutral-variant tone 60
*/

// Generated by https://material-foundation.github.io/material-theme-builder
export const themeColors: ThemeColorsOptions = {
    "light": {
        "primary": "0 105 110",
        "surfaceTint": "0 105 110",
        "onPrimary": "255 255 255",
        "primaryContainer": "156 240 246",
        "onPrimaryContainer": "0 79 83",
        "secondary": "65 95 145",
        "onSecondary": "255 255 255",
        "secondaryContainer": "214 227 255",
        "onSecondaryContainer": "39 71 119",
        "tertiary": "78 95 125",
        "onTertiary": "255 255 255",
        "tertiaryContainer": "214 227 255",
        "onTertiaryContainer": "54 71 100",
        "error": "186 26 26",
        "onError": "255 255 255",
        "errorContainer": "255 218 214",
        "onErrorContainer": "147 0 10",
        "success": "64 128 88",
        "onSuccess": "240 252 245",
        "successContainer": "193 230 207",
        "onSuccessContainer": "25 51 35",
        "successFixed": "193 230 207",
        "onSuccessFixed": "25 51 35",
        "successFixedDim": "178 230 198",
        "onSuccessFixedVariant": "51 102 70",
        "warning": "128 105 13",
        "onWarning": "252 248 230",
        "warningContainer": "230 216 164",
        "onWarningContainer": "51 42 5",
        "warningFixed": "230 216 164",
        "onWarningFixed": "51 42 5",
        "warningFixedDim": "230 211 137",
        "onWarningFixedVariant": "102 84 10",
        "background": "244 250 250",
        "onBackground": "22 29 29",
        "surface": "244 250 250",
        "onSurface": "22 29 29",
        "surfaceVariant": "218 228 229",
        "onSurfaceVariant": "63 73 73",
        "outline": "111 121 121",
        "outlineVariant": "190 200 201",
        "shadow": "0 0 0",
        "scrim": "0 0 0",
        "inverseSurface": "43 50 50",
        "inverseOnSurface": "236 242 242",
        "inversePrimary": "128 212 217",
        "primaryFixed": "156 240 246",
        "onPrimaryFixed": "0 32 33",
        "primaryFixedDim": "128 212 217",
        "onPrimaryFixedVariant": "0 79 83",
        "secondaryFixed": "214 227 255",
        "onSecondaryFixed": "0 27 62",
        "secondaryFixedDim": "170 199 255",
        "onSecondaryFixedVariant": "39 71 119",
        "tertiaryFixed": "214 227 255",
        "onTertiaryFixed": "8 28 54",
        "tertiaryFixedDim": "182 199 233",
        "onTertiaryFixedVariant": "54 71 100",
        "surfaceDim": "213 219 219",
        "surfaceBright": "244 250 250",
        "surfaceContainerLowest": "255 255 255",
        "surfaceContainerLow": "239 245 245",
        "surfaceContainer": "233 239 239",
        "surfaceContainerHigh": "227 233 233",
        "surfaceContainerHighest": "221 228 228"
    },
    "dark": {
        "primary": "128 212 217",
        "surfaceTint": "128 212 217",
        "onPrimary": "0 55 57",
        "primaryContainer": "0 79 83",
        "onPrimaryContainer": "156 240 246",
        "secondary": "170 199 255",
        "onSecondary": "10 48 95",
        "secondaryContainer": "39 71 119",
        "onSecondaryContainer": "214 227 255",
        "tertiary": "182 199 233",
        "onTertiary": "31 49 76",
        "tertiaryContainer": "54 71 100",
        "onTertiaryContainer": "214 227 255",
        "error": "255 180 171",
        "onError": "105 0 5",
        "errorContainer": "147 0 10",
        "onErrorContainer": "255 218 214",
        "success": "178 230 198",
        "onSuccess": "38 76 53",
        "successContainer": "51 102 70",
        "onSuccessContainer": "193 230 207",
        "successFixed": "193 230 207",
        "onSuccessFixed": "25 51 35",
        "successFixedDim": "178 230 198",
        "onSuccessFixedVariant": "51 102 70",
        "warning": "230 211 137",
        "onWarning": "76 63 8",
        "warningContainer": "102 84 10",
        "onWarningContainer": "230 216 164",
        "warningFixed": "230 216 164",
        "onWarningFixed": "51 42 5",
        "warningFixedDim": "230 211 137",
        "onWarningFixedVariant": "102 84 10",
        "background": "14 20 21",
        "onBackground": "221 228 228",
        "surface": "14 20 21",
        "onSurface": "221 228 228",
        "surfaceVariant": "63 73 73",
        "onSurfaceVariant": "190 200 201",
        "outline": "137 147 147",
        "outlineVariant": "63 73 73",
        "shadow": "0 0 0",
        "scrim": "0 0 0",
        "inverseSurface": "221 228 228",
        "inverseOnSurface": "43 50 50",
        "inversePrimary": "0 105 110",
        "primaryFixed": "156 240 246",
        "onPrimaryFixed": "0 32 33",
        "primaryFixedDim": "128 212 217",
        "onPrimaryFixedVariant": "0 79 83",
        "secondaryFixed": "214 227 255",
        "onSecondaryFixed": "0 27 62",
        "secondaryFixedDim": "170 199 255",
        "onSecondaryFixedVariant": "39 71 119",
        "tertiaryFixed": "214 227 255",
        "onTertiaryFixed": "8 28 54",
        "tertiaryFixedDim": "182 199 233",
        "onTertiaryFixedVariant": "54 71 100",
        "surfaceDim": "14 20 21",
        "surfaceBright": "52 58 59",
        "surfaceContainerLowest": "9 15 16",
        "surfaceContainerLow": "22 29 29",
        "surfaceContainer": "26 33 33",
        "surfaceContainerHigh": "37 43 43",
        "surfaceContainerHighest": "48 54 54"
    },
    "palettes": {
        "primary": {
            "0": "0 0 0",
            "5": "0 20 21",
            "10": "0 32 33",
            "15": "0 43 45",
            "20": "0 55 57",
            "25": "0 67 70",
            "30": "0 79 83",
            "35": "0 92 96",
            "40": "0 105 110",
            "50": "0 132 138",
            "60": "51 159 165",
            "70": "84 186 192",
            "80": "114 214 220",
            "90": "143 242 248",
            "95": "192 251 255",
            "98": "231 254 255",
            "99": "242 255 255",
            "100": "255 255 255"
        },
        "secondary": {
            "0": "0 0 0",
            "5": "0 16 42",
            "10": "0 27 62",
            "15": "0 37 81",
            "20": "0 47 100",
            "25": "0 58 120",
            "30": "0 69 141",
            "35": "0 81 163",
            "40": "0 93 185",
            "50": "17 117 227",
            "60": "64 144 255",
            "70": "122 172 255",
            "80": "170 199 255",
            "90": "214 227 255",
            "95": "236 240 255",
            "98": "249 249 255",
            "99": "253 251 255",
            "100": "255 255 255"
        },
        "tertiary": {
            "0": "0 0 0",
            "5": "3 17 37",
            "10": "14 28 49",
            "15": "25 38 59",
            "20": "36 49 70",
            "25": "47 60 82",
            "30": "58 71 94",
            "35": "70 83 106",
            "40": "82 95 119",
            "50": "106 119 144",
            "60": "132 145 171",
            "70": "158 172 198",
            "80": "186 199 227",
            "90": "214 227 255",
            "95": "236 240 255",
            "98": "249 249 255",
            "99": "253 251 255",
            "100": "255 255 255"
        },
        "neutral": {
            "0": "0 0 0",
            "5": "15 17 18",
            "10": "25 28 28",
            "15": "35 38 38",
            "20": "46 49 49",
            "25": "57 60 60",
            "30": "69 71 71",
            "35": "80 83 83",
            "40": "92 95 95",
            "50": "117 119 119",
            "60": "143 145 145",
            "70": "170 171 171",
            "80": "197 199 198",
            "90": "225 227 226",
            "95": "240 241 240",
            "98": "248 249 249",
            "99": "251 252 252",
            "100": "255 255 255"
        },
        "neutralVariant": {
            "0": "0 0 0",
            "5": "11 18 19",
            "10": "22 29 29",
            "15": "32 39 39",
            "20": "42 50 50",
            "25": "53 61 61",
            "30": "65 72 73",
            "35": "76 84 84",
            "40": "88 96 96",
            "50": "113 120 121",
            "60": "138 146 146",
            "70": "165 173 173",
            "80": "192 200 200",
            "90": "220 228 228",
            "95": "235 242 242",
            "98": "243 251 251",
            "99": "246 254 254",
            "100": "255 255 255"
        }
    }
}
const palettes: any = {}
Object.entries(themeColors.palettes)
    .forEach(e => {
        Object.keys(e[1])
            .forEach(k => {
                palettes[e[0] + k] = (e[1] as any)[k];
            })
    })

const light = { ...themeColors.light, ...palettes }
const dark = { ...themeColors.dark, ...palettes }

export const themes = {
    light: vars(light),
    dark: vars(dark),
};
