/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ["class"],
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}",],
    plugins: [
        require("tailwindcss-animate")
    ],
    theme: {
        extend: {
            boxShadowColor: '#000',
            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)'
            },
            colors: {
                "primary": "rgb(var(--primary) / <alpha-value>)",
                "surface-tint": "rgb(var(--surfaceTint) / <alpha-value>)",
                "on-primary": "rgb(var(--onPrimary) / <alpha-value>)",
                "primary-container": "rgb(var(--primaryContainer) / <alpha-value>)",
                "on-primary-container": "rgb(var(--onPrimaryContainer) / <alpha-value>)",
                "secondary": "rgb(var(--secondary) / <alpha-value>)",
                "on-secondary": "rgb(var(--onSecondary) / <alpha-value>)",
                "secondary-container": "rgb(var(--secondaryContainer) / <alpha-value>)",
                "on-secondary-container": "rgb(var(--onSecondaryContainer) / <alpha-value>)",
                "tertiary": "rgb(var(--tertiary) / <alpha-value>)",
                "on-tertiary": "rgb(var(--onTertiary) / <alpha-value>)",
                "tertiary-container": "rgb(var(--tertiaryContainer) / <alpha-value>)",
                "on-tertiary-container": "rgb(var(--onTertiaryContainer) / <alpha-value>)",
                "error": "rgb(var(--error) / <alpha-value>)",
                "on-error": "rgb(var(--onError) / <alpha-value>)",
                "error-container": "rgb(var(--errorContainer) / <alpha-value>)",
                "on-error-container": "rgb(var(--onErrorContainer) / <alpha-value>)",
                "success": "rgb(var(--success) / <alpha-value>)",
                "on-success": "rgb(var(--onSuccess) / <alpha-value>)",
                "success-container": "rgb(var(--successContainer) / <alpha-value>)",
                "on-success-container": "rgb(var(--onSuccessContainer) / <alpha-value>)",
                "success-fixed": "rgb(var(--successFixed) / <alpha-value>)",
                "on-success-fixed": "rgb(var(--onSuccessFixed) / <alpha-value>)",
                "success-fixed-dim": "rgb(var(--successFixedDim) / <alpha-value>)",
                "on-success-fixed-variant": "rgb(var(--onSuccessFixedVariant) / <alpha-value>)",
                "background": "rgb(var(--background) / <alpha-value>)",
                "on-background": "rgb(var(--onBackground) / <alpha-value>)",
                "surface": "rgb(var(--surface) / <alpha-value>)",
                "on-surface": "rgb(var(--onSurface) / <alpha-value>)",
                "surface-variant": "rgb(var(--surfaceVariant) / <alpha-value>)",
                "on-surface-variant": "rgb(var(--onSurfaceVariant) / <alpha-value>)",
                "outline": "rgb(var(--outline) / <alpha-value>)",
                "outline-variant": "rgb(var(--outlineVariant) / <alpha-value>)",
                "shadow": "rgb(var(--shadow) / <alpha-value>)",
                "scrim": "rgb(var(--scrim) / <alpha-value>)",
                "inverse-surface": "rgb(var(--inverseSurface) / <alpha-value>)",
                "inverse-on-surface": "rgb(var(--inverseOnSurface) / <alpha-value>)",
                "inverse-primary": "rgb(var(--inversePrimary) / <alpha-value>)",
                "primary-fixed": "rgb(var(--primaryFixed) / <alpha-value>)",
                "on-primary-fixed": "rgb(var(--onPrimaryFixed) / <alpha-value>)",
                "primary-fixed-dim": "rgb(var(--primaryFixedDim) / <alpha-value>)",
                "on-primary-fixed-variant": "rgb(var(--onPrimaryFixedVariant) / <alpha-value>)",
                "secondary-fixed": "rgb(var(--secondaryFixed) / <alpha-value>)",
                "on-secondary-fixed": "rgb(var(--onSecondaryFixed) / <alpha-value>)",
                "secondary-fixed-dim": "rgb(var(--secondaryFixedDim) / <alpha-value>)",
                "on-secondary-fixed-variant": "rgb(var(--onSecondaryFixedVariant) / <alpha-value>)",
                "tertiary-fixed": "rgb(var(--tertiaryFixed) / <alpha-value>)",
                "on-tertiary-fixed": "rgb(var(--onTertiaryFixed) / <alpha-value>)",
                "tertiary-fixed-dim": "rgb(var(--tertiaryFixedDim) / <alpha-value>)",
                "on-tertiary-fixed-variant": "rgb(var(--onTertiaryFixedVariant) / <alpha-value>)",
                "surface-dim": "rgb(var(--surfaceDim) / <alpha-value>)",
                "surface-bright": "rgb(var(--surfaceBright) / <alpha-value>)",
                "surface-container-lowest": "rgb(var(--surfaceContainerLowest) / <alpha-value>)",
                "surface-container-low": "rgb(var(--surfaceContainerLow) / <alpha-value>)",
                "surface-container": "rgb(var(--surfaceContainer) / <alpha-value>)",
                "surface-container-high": "rgb(var(--surfaceContainerHigh) / <alpha-value>)",
                "surface-container-highest": "rgb(var(--surfaceContainerHighest) / <alpha-value>)",
                "warning": "rgb(var(--warning) / <alpha-value>)",
                "on-warning": "rgb(var(--onWarning) / <alpha-value>)",
                "warning-container": "rgb(var(--warningContainer) / <alpha-value>)",
                "on-warning-container": "rgb(var(--onWarningContainer) / <alpha-value>)",
                "warning-fixed": "rgb(var(--warningFixed) / <alpha-value>)",
                "on-warning-fixed": "rgb(var(--onWarningFixed) / <alpha-value>)",
                "warning-fixed-dim": "rgb(var(--warningFixedDim) / <alpha-value>)",
                "on-warning-fixed-variant": "rgb(var(--onWarningFixedVariant) / <alpha-value>)",

                "primary-0": "rgb(var(--primary0) / <alpha-value>)",
                "primary-5": "rgb(var(--primary5) / <alpha-value>)",
                "primary-10": "rgb(var(--primary10) / <alpha-value>)",
                "primary-15": "rgb(var(--primary15) / <alpha-value>)",
                "primary-20": "rgb(var(--primary20) / <alpha-value>)",
                "primary-25": "rgb(var(--primary25) / <alpha-value>)",
                "primary-30": "rgb(var(--primary30) / <alpha-value>)",
                "primary-35": "rgb(var(--primary35) / <alpha-value>)",
                "primary-40": "rgb(var(--primary40) / <alpha-value>)",
                "primary-50": "rgb(var(--primary50) / <alpha-value>)",
                "primary-60": "rgb(var(--primary60) / <alpha-value>)",
                "primary-70": "rgb(var(--primary70) / <alpha-value>)",
                "primary-80": "rgb(var(--primary80) / <alpha-value>)",
                "primary-90": "rgb(var(--primary90) / <alpha-value>)",
                "primary-95": "rgb(var(--primary95) / <alpha-value>)",
                "primary-98": "rgb(var(--primary98) / <alpha-value>)",
                "primary-99": "rgb(var(--primary99) / <alpha-value>)",
                "primary-100": "rgb(var(--primary100) / <alpha-value>)",

                "secondary-0": "rgb(var(--secondary0) / <alpha-value>)",
                "secondary-5": "rgb(var(--secondary5) / <alpha-value>)",
                "secondary-10": "rgb(var(--secondary10) / <alpha-value>)",
                "secondary-15": "rgb(var(--secondary15) / <alpha-value>)",
                "secondary-20": "rgb(var(--secondary20) / <alpha-value>)",
                "secondary-25": "rgb(var(--secondary25) / <alpha-value>)",
                "secondary-30": "rgb(var(--secondary30) / <alpha-value>)",
                "secondary-35": "rgb(var(--secondary35) / <alpha-value>)",
                "secondary-40": "rgb(var(--secondary40) / <alpha-value>)",
                "secondary-50": "rgb(var(--secondary50) / <alpha-value>)",
                "secondary-60": "rgb(var(--secondary60) / <alpha-value>)",
                "secondary-70": "rgb(var(--secondary70) / <alpha-value>)",
                "secondary-80": "rgb(var(--secondary80) / <alpha-value>)",
                "secondary-90": "rgb(var(--secondary90) / <alpha-value>)",
                "secondary-95": "rgb(var(--secondary95) / <alpha-value>)",
                "secondary-98": "rgb(var(--secondary98) / <alpha-value>)",
                "secondary-99": "rgb(var(--secondary99) / <alpha-value>)",
                "secondary-100": "rgb(var(--secondary100) / <alpha-value>)",

                "tertiary-0": "rgb(var(--tertiary0) / <alpha-value>)",
                "tertiary-5": "rgb(var(--tertiary5) / <alpha-value>)",
                "tertiary-10": "rgb(var(--tertiary10) / <alpha-value>)",
                "tertiary-15": "rgb(var(--tertiary15) / <alpha-value>)",
                "tertiary-20": "rgb(var(--tertiary20) / <alpha-value>)",
                "tertiary-25": "rgb(var(--tertiary25) / <alpha-value>)",
                "tertiary-30": "rgb(var(--tertiary30) / <alpha-value>)",
                "tertiary-35": "rgb(var(--tertiary35) / <alpha-value>)",
                "tertiary-40": "rgb(var(--tertiary40) / <alpha-value>)",
                "tertiary-50": "rgb(var(--tertiary50) / <alpha-value>)",
                "tertiary-60": "rgb(var(--tertiary60) / <alpha-value>)",
                "tertiary-70": "rgb(var(--tertiary70) / <alpha-value>)",
                "tertiary-80": "rgb(var(--tertiary80) / <alpha-value>)",
                "tertiary-90": "rgb(var(--tertiary90) / <alpha-value>)",
                "tertiary-95": "rgb(var(--tertiary95) / <alpha-value>)",
                "tertiary-98": "rgb(var(--tertiary98) / <alpha-value>)",
                "tertiary-99": "rgb(var(--tertiary99) / <alpha-value>)",
                "tertiary-100": "rgb(var(--tertiary100) / <alpha-value>)",

                "neutral-0": "rgb(var(--neutral0) / <alpha-value>)",
                "neutral-5": "rgb(var(--neutral5) / <alpha-value>)",
                "neutral-10": "rgb(var(--neutral10) / <alpha-value>)",
                "neutral-15": "rgb(var(--neutral15) / <alpha-value>)",
                "neutral-20": "rgb(var(--neutral20) / <alpha-value>)",
                "neutral-25": "rgb(var(--neutral25) / <alpha-value>)",
                "neutral-30": "rgb(var(--neutral30) / <alpha-value>)",
                "neutral-35": "rgb(var(--neutral35) / <alpha-value>)",
                "neutral-40": "rgb(var(--neutral40) / <alpha-value>)",
                "neutral-50": "rgb(var(--neutral50) / <alpha-value>)",
                "neutral-60": "rgb(var(--neutral60) / <alpha-value>)",
                "neutral-70": "rgb(var(--neutral70) / <alpha-value>)",
                "neutral-80": "rgb(var(--neutral80) / <alpha-value>)",
                "neutral-90": "rgb(var(--neutral90) / <alpha-value>)",
                "neutral-95": "rgb(var(--neutral95) / <alpha-value>)",
                "neutral-98": "rgb(var(--neutral98) / <alpha-value>)",
                "neutral-99": "rgb(var(--neutral99) / <alpha-value>)",
                "neutral-100": "rgb(var(--neutral100) / <alpha-value>)",

                "neutral-variant-0": "rgb(var(--neutralVariant0) / <alpha-value>)",
                "neutral-variant-5": "rgb(var(--neutralVariant5) / <alpha-value>)",
                "neutral-variant-10": "rgb(var(--neutralVariant10) / <alpha-value>)",
                "neutral-variant-15": "rgb(var(--neutralVariant15) / <alpha-value>)",
                "neutral-variant-20": "rgb(var(--neutralVariant20) / <alpha-value>)",
                "neutral-variant-25": "rgb(var(--neutralVariant25) / <alpha-value>)",
                "neutral-variant-30": "rgb(var(--neutralVariant30) / <alpha-value>)",
                "neutral-variant-35": "rgb(var(--neutralVariant35) / <alpha-value>)",
                "neutral-variant-40": "rgb(var(--neutralVariant40) / <alpha-value>)",
                "neutral-variant-50": "rgb(var(--neutralVariant50) / <alpha-value>)",
                "neutral-variant-60": "rgb(var(--neutralVariant60) / <alpha-value>)",
                "neutral-variant-70": "rgb(var(--neutralVariant70) / <alpha-value>)",
                "neutral-variant-80": "rgb(var(--neutralVariant80) / <alpha-value>)",
                "neutral-variant-90": "rgb(var(--neutralVariant90) / <alpha-value>)",
                "neutral-variant-95": "rgb(var(--neutralVariant95) / <alpha-value>)",
                "neutral-variant-98": "rgb(var(--neutralVariant98) / <alpha-value>)",
                "neutral-variant-99": "rgb(var(--neutralVariant99) / <alpha-value>)",
                "neutral-variant-100": "rgb(var(--neutralVariant100) / <alpha-value>)",
            },
        }
    },
}