import type { ThemeColorsOptions, ThemeOptions } from "./types/theme";

export const defaultTheme: ThemeOptions = {
    "mode": "dark",
    "radius": "0.5rem",
    "scrollbarWidth": "0.5rem",
    "scrollbarHeight": "0.5rem",
    "scrollbarBorderRadius": "5px",
    "scrollbarThumbRounded": "9999px"
}

export const themeColors: ThemeColorsOptions = {
    light: {
        "primary": "#2a5ea7",
        "onPrimary": "#ffffff",
        "primaryContainer": "#d6e3ff",
        "onPrimaryContainer": "#001b3e",
        "secondary": "#565f71",
        "onSecondary": "#ffffff",
        "secondaryContainer": "#dae2f9",
        "onSecondaryContainer": "#131c2b",
        "tertiary": "#705575",
        "onTertiary": "#ffffff",
        "tertiaryContainer": "#fad8fd",
        "onTertiaryContainer": "#28132e",
        "error": "#ba1a1a",
        "onError": "#ffffff",
        "errorContainer": "#ffdad6",
        "onErrorContainer": "#410002",
        "background": "#fdfbff",
        "onBackground": "#1a1b1e",
        "surface": "#fdfbff",
        "onSurface": "#1a1b1e",
        "surfaceVariant": "#e0e2ec",
        "onSurfaceVariant": "#44474e",
        "outline": "#74777f",
        "outlineVariant": "#c4c6d0",
        "shadow": "#000000",
        "scrim": "#000000",
        "inverseSurface": "#2f3033",
        "inverseOnSurface": "#f1f0f4",
        "inversePrimary": "#aac7ff",
        "onDisabled": "rgba(26, 27, 30, 0.38)",
        "disabled": "rgba(26, 27, 30, 0.12)",
        "success": "#006e2f",
        "onSuccess": "#ffffff",
        "warning": "#855300",
        "onWarning": "#ffffff",
        "scrollbarBg": "#fdfbff",
        "scrollbarThumbBg": "#1a1b1e"
    },
    dark: {
        "primary": "#aac7ff",
        "onPrimary": "#002f64",
        "primaryContainer": "#00458e",
        "onPrimaryContainer": "#d6e3ff",
        "secondary": "#bec6dc",
        "onSecondary": "#283141",
        "secondaryContainer": "#3e4759",
        "onSecondaryContainer": "#dae2f9",
        "tertiary": "#ddbce0",
        "onTertiary": "#3f2844",
        "tertiaryContainer": "#573e5c",
        "onTertiaryContainer": "#fad8fd",
        "error": "#ffb4ab",
        "onError": "#690005",
        "errorContainer": "#93000a",
        "onErrorContainer": "#ffb4ab",
        "background": "#1a1b1e",
        "onBackground": "#e3e2e6",
        "surface": "#1a1b1e",
        "onSurface": "#e3e2e6",
        "surfaceVariant": "#44474e",
        "onSurfaceVariant": "#c4c6d0",
        "outline": "#8e9099",
        "outlineVariant": "#44474e",
        "shadow": "#000000",
        "scrim": "#000000",
        "inverseSurface": "#e3e2e6",
        "inverseOnSurface": "#2f3033",
        "inversePrimary": "#2a5ea7",
        "onDisabled": "rgba(227, 226, 230, 0.38)",
        "disabled": "rgba(227, 226, 230, 0.12)",
        "success": "#4ae176",
        "onSuccess": "#003915",
        "warning": "#ffb95f",
        "onWarning": "#472a00",
        "scrollbarBg": "#1a1b1e",
        "scrollbarThumbBg": "#e3e2e6"
    }
}
